name = "en-santiago"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "en-santiago-db"
database_id = "083ae5ed-b15f-4ff3-abcf-b3a3b666bb79"

[vars]
R2_FOLDER = "santiago"
JWT_SECRET = "ensantiago_jwt_secret_2024"
